<?php

class Euler extends Math {

    /**
     * @title - Multiples of 3 and 5
     * If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9.
     * The sum of these multiples is 23. Find the sum of all the multiples of 3 or 5 below 1000.
     */
    public function problem_1()
    {
        for($i = 1; $i < 1000; $i++) {
            if(!($i % 3) || !($i % 5)) {
                isset($solution) ? $solution += $i : $solution = $i;
            }
        }
        return $solution;
    }

    /**
     * @title - Even Fibonacci numbers
     * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
     * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
     * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
     */
    public function problem_2()
    {
        $limit = 4000000;
        $last = 1;
        $current = 2;

        while(true) {
            if(!($current % 2)) {
                isset($solution) ? $solution += $current : $solution = $current;
            }

            $old = $last;
            $last = $current;
            $current = $old + $current;

            if($current > $limit) {
                break;
            }
        }
        return $solution;
    }

    /**
     * @title - Largest prime factor
     * The prime factors of 13195 are 5, 7, 13 and 29.
     * What is the largest prime factor of the number 600851475143 ?
     */
    public function problem_3()
    {
        $nr = 600851475143;
        $primeSieve = array_flip(array(2=>-1) + $this->sieve(10000));
        foreach($primeSieve as $ps) {
            if(bcmod($nr,$ps) == 0) {
                $solution = $ps;
            }
        }
        return $solution;
    }

    /**
     * @title - Largest palindrome product
     * A palindromic number reads the same both ways. The largest palindrome
     * made from the product of two 2-digit numbers is 9009 = 91 × 99.
     * Find the largest palindrome made from the product of two 3-digit numbers.
     */
    public function problem_4()
    {
        for($i = 999; $i > 800; $i--) {
            for($j = 999; $j > 800; $j--) {
                $p = $i * $j;

                if(substr($p,0,3) == strrev(substr($p,-3))) {
                    $solution[] = $p;
                }
            }
        }

        sort($solution);
        return end($solution);
    }

    /**
     * @title - Smallest multiple
     * 2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.
     * What is the smallest number that is evenly divisible by all of the numbers from 1 to 20?
     */
    // public function problem_5()
    // {
    //     $solution = $inc = 2520;
    //     function checkDiv($i){
    //         for($k=11;$k<=20;$k++) {
    //             if(strpos( ($i / $k), '.') !== false) {
    //                 return false;
    //             }
    //         }
    //         return true;
    //     }
    //     while(!checkDiv($solution)) {
    //         $solution = $solution + $inc;
    //     }
    // }


    /**
     * @title - Sum square difference
     *
     */

    /**
     * @title - 10001st prime
     *
     */

    /**
     * @title - Largest product in a series
     *
     */

    /**
     * @title - Special Pythagorean triplet
     *
     */

    /**
     * @title - Summation of primes
     *
     */

    /**
     * @title - Largest product in a grid
     *
     */

    /**
     * @title - Highly divisible triangular number
     *
     */

    /**
     * @title - Large sum
     *
     */

    /**
     * @title - Longest Collatz sequence
     *
     */

    /**
     * @title - Lattice paths
     *
     */

    /**
     * @title - Power digit sum
     *
     */

    /**
     * @title - Number letter counts
     *
     */

    /**
     * @title - Maximum path sum I
     *
     */

    /**
     * @title - Counting Sundays
     *
     */

    /**
     * @title - Factorial digit sum
     *
     */

    /**
     * @title - Amicable numbers
     *
     */

    /**
     * @title - Names scores
     *
     */

    /**
     * @title - Non-abundant sums
     *
     */

    /**
     * @title - Lexicographic permutations
     *
     */

    /**
     * @title - 1000-digit Fibonacci number
     *
     */

    /**
     * @title - Reciprocal cycles
     *
     */

    /**
     * @title - Quadratic primes
     *
     */

    /**
     * @title - Number spiral diagonals
     *
     */

    /**
     * @title - Distinct powers
     *
     */

}